// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Vector3 } from "./Vector3";

export type LineComp = { line: string, position: Vector3, cam_look_at: Vector3, cam_position: Vector3 | null, color: Color | null, end_positiion: Vector3 | null, cam_end_position: Vector3 | null, cam_end_look_at: Vector3 | null, };
