// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Vector3 } from "three";


export type LineComp = {
  line: string;
  position: Vector3;
  cam_look_at: Vector3;
  color: Color | null;
  cam_position: Vector3 | null;
  end_positiion: Vector3 | null;
};
