// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineComp } from "./LineComp";

export type LoadSong = { title: string, lines: Array<LineComp>, };

