-- Your SQL goes here
CREATE EXTENSION IF NOT EXISTS "vector";

CREATE TABLE IF NOT EXISTS song (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lines (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line TEXT NOT NULL,
  song_id int NOT NULL,
  position VECTOR(3) NOT NULL,
  cam_position VECTOR(3) NOT NULL,
  cam_look_at VECTOR(3) NOT NULL,
  keep_n_last int[] NOT NULL check (array_position(keep_n_last, null) is null),

  end_position VECTOR(3),
  cam_end_position VECTOR(3),
  cam_end_look_at VECTOR(3),

  FOREIGN KEY (song_id) REFERENCES song(id) ON DELETE CASCADE
);

