-- Your SQL goes here
CREATE EXTENSION IF NOT EXISTS "vector";

CREATE TYPE animation AS ENUM ('in', 'out', 'in_out');

CREATE TABLE IF NOT EXISTS song (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lines (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line TEXT NOT NULL,
  song_id INT NOT NULL,
  position VECTOR(3) NOT NULL,
  cam_position VECTOR(3) NOT NULL,
  cam_position_duration INT,
  cam_look_at VECTOR(3) NOT NULL,
  keep_n_last INT NOT NULL DEFAULT 0,

  rotation VECTOR(3),
  text_animation animation,
  text_position_duration INT,
  cam_rotation VECTOR(3),
  end_position VECTOR(3),
  cam_end_position VECTOR(3),
  cam_end_look_at VECTOR(3),

  FOREIGN KEY (song_id) REFERENCES song(id) ON DELETE CASCADE
);

